export const FETCH_FILM_PENDING="FETCH_FILM_PENDING";
export const FETCH_FILM_DATA="FETCH_FILM_DATA"
export const FETCH_FILM_ERROR="FETCH_FILM_ERROR"
export const FETCH_FILM_BY_SEARCH="FETCH_FILM_BY_SEARCH"
export const ADD_TO_LIST="ADD_TO_LIST"
export const GET_LIST="GET_LIST"
export const REMOVE_FROM_LIST="REMOVE_FROM_LIST"